[theme]
name = "material-darker"

[colors]
AlertInfo = "#c3e88d"
AlertWarn = "#ffcb6b"
AlertError = "#ff5370"
Annotation = "#c792ea"
Base = "#eeffff"
Guidance = "#90a4ae"
Important = "#ff9800"
Title = "#c792ea"
