# Leader
set -g prefix C-s
unbind C-b
bind C-s send-prefix

# Vim-like motions
set -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Mouse
set -g mouse on

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"
